=== 15Carmen/XSD/Ejercicio19/inventores3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="inventores3">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="inventor" maxOccurs="6">
                    <xs:complexType>

                        <xs:sequence>
                            <xs:element ref="invento"/>
                            <xs:element ref="nombre"/>
                            <xs:element ref="apellido"/>

                        </xs:sequence>

                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="invento" type="xs:string"/>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="apellido" type="xs:string"/>

</xs:schema>

=== 15Carmen/XSD/Ejercicio19/Ejercicio19_parte1.xml
<?xml version="1.0" encoding="UTF-8"?>

<inventores3 xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
             xs:noNamespaceSchemaLocation="inventores3.xsd">

    <inventor>
        <invento>"Mando a distancia"</invento>
        <nombre>Mario</nombre>
        <apellido>Casas</apellido>
    </inventor>

    <inventor>
        <invento>"BolÃ­grafo"</invento>
        <nombre>Isa</nombre>
        <apellido>Katarina</apellido>
    </inventor>

</inventores3>
