=== 15Carmen/XSD/Ejercicio14.2/aeropuertoss2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="aeropuertos">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="aeropuerto" minOccurs="3" maxOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="vuelo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="numero" type="xs:short"/>
                            <xs:element name="precio" type="xs:decimal"/>
                            <xs:element name="despegue" type="xs:dateTime"/>
                            <xs:element name="diaAterrizaje" type="xs:date"/>
                            <xs:element name="horaAterrizaje" type="xs:time"/>
                            <xs:element name="numeroPasajeros" type="xs:positiveInteger"/>
                            <xs:element name="metrosRecorridos" type="xs:long"/>
                            <xs:element name="tipoAvion" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 15Carmen/XSD/Ejercicio14.2/Ejercicio14.2.xml
<?xml version="1.0" encoding="UTF-8"?>

<aeropuertos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
             xs:noNamespaceSchemaLocation="aeropuertoss2.xsd">
    <aeropuerto>
        <nombre>Berlín Schönefeld (SFX)</nombre>
    </aeropuerto>
    <aeropuerto>
        <nombre>Berlín Tempelhof (THF)</nombre>
    </aeropuerto>
    <aeropuerto>
        <nombre>Madrid Barajas (THF)</nombre>
    </aeropuerto>
    <vuelo>
        <numero>12345</numero>
        <precio>100.99</precio>
        <despegue>2022-03-05T22:15:00 </despegue>
        <diaAterrizaje>2022-03-06</diaAterrizaje>
        <horaAterrizaje>05:30:00</horaAterrizaje>
        <numeroPasajeros>50</numeroPasajeros>
        <metrosRecorridos>12346789</metrosRecorridos>
        <tipoAvion>1</tipoAvion>
    </vuelo>

</aeropuertos>
