=== 15Carmen/XSD/Ejercicio18/inventores2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="inventores2">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="inventor" maxOccurs="6">
                    <xs:complexType>

                        <xs:sequence>
                            <xs:element name="invento" type="xs:string"/>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string"/>

                            <xs:choice>
                                <xs:element name="id" type="xs:string"/>
                                <xs:element name="dni" type="xs:string"/>
                            </xs:choice>

                        </xs:sequence>

                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 15Carmen/XSD/Ejercicio18/Ejercicio18.xml
<?xml version="1.0" encoding="UTF-8"?>

<inventores2 xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
            xs:noNamespaceSchemaLocation="inventores2.xsd">

    <inventor>
        <invento>"Mando a distancia"</invento>
        <nombre>Mario</nombre>
        <apellido>Casas</apellido>
        <dni>49117682D</dni>
    </inventor>

    <inventor>
        <invento>"BolÃ­grafo"</invento>
        <nombre>Isa</nombre>
        <apellido>Katarina</apellido>
        <id>1234</id>
    </inventor>

</inventores2>
