=== 15Carmen/XSD/RepasoExamen/Actividad_3/XSD_Actividad3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="calificaciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumnos">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="datos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellidos" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="materia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="OACE">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cuestionario" type="xs:double"/>
                                                    <xs:element name="tareas" type="xs:double"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="EEE">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cuestionario" type="xs:double"/>
                                                    <xs:element name="tareas" type="xs:double"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="materia2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="OACE">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cuestionario" type="xs:double"/>
                                                    <xs:element name="tareas" type="xs:double"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="EEE">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cuestionario" type="xs:double"/>
                                                    <xs:element name="tareas" type="xs:double"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 15Carmen/XSD/RepasoExamen/Actividad_3/Actividad3.xml
<calificaciones xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
                xs:noNamespaceSchemaLocation="XSD_Actividad3.xsd">

    <alumnos>
        <datos>
            <nombre>Carmen</nombre>
            <apellidos>Martín Núñez</apellidos>
        </datos>

        <materia>
            <OACE>
                <cuestionario>8.5</cuestionario>
                <tareas>9</tareas>
            </OACE>

            <EEE>
                <cuestionario>9.3</cuestionario>
                <tareas>7</tareas>
            </EEE>
        </materia>

        <materia2>
            <OACE>
                <cuestionario>7.9</cuestionario>
                <tareas>6.2</tareas>
            </OACE>

            <EEE>
                <cuestionario>8.9</cuestionario>
                <tareas>10</tareas>
            </EEE>
        </materia2>
    </alumnos>

</calificaciones>
