<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE moviles [
        <!ELEMENT moviles (movil+)>
        <!ELEMENT movil (modelo, precio, fabricante, color)>
        <!ELEMENT modelo (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ELEMENT fabricante (#PCDATA)>
        <!ELEMENT color (#PCDATA)>
        ]>
<moviles>
    <movil>
        <modelo>iPhone XS</modelo>
        <precio>400€</precio>
        <fabricante>Apple</fabricante>
        <color>rojo</color>
    </movil>

    <movil>
        <modelo>Galaxy s3</modelo>
        <precio>380€</precio>
        <fabricante>Samsung</fabricante>
        <color>plateado</color>
    </movil>

</moviles>